### ISSUE TITLE
Does this also work for windows 8 apps?

### ISSUE THREAD

**Issue by fritsjan** [mutualmobile/cordova-bluetoothle#1]
Hi, I need to develop an interface for ios, android and for windows 8 (desktop/app).
With phonegap you can do all of the above, but I need to interface with a ble device, hence my question.

Thanks for your reply!

**Comment by zship** [comment]
Hi, @fritsjan. Unfortunately no, we don't support Windows 8 yet. It's a definite "nice to have" that I'd like to add, but we don't have concrete plans to do so because we don't yet have a need. You might try https://github.com/randdusing/BluetoothLE, of which this project is a fork.
